// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package dex

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_LiquidityPool             protoreflect.MessageDescriptor
	fd_LiquidityPool_index       protoreflect.FieldDescriptor
	fd_LiquidityPool_token0      protoreflect.FieldDescriptor
	fd_LiquidityPool_token1      protoreflect.FieldDescriptor
	fd_LiquidityPool_amount0     protoreflect.FieldDescriptor
	fd_LiquidityPool_amount1     protoreflect.FieldDescriptor
	fd_LiquidityPool_totalShares protoreflect.FieldDescriptor
)

func init() {
	file_cosmuni_dex_liquidity_pool_proto_init()
	md_LiquidityPool = File_cosmuni_dex_liquidity_pool_proto.Messages().ByName("LiquidityPool")
	fd_LiquidityPool_index = md_LiquidityPool.Fields().ByName("index")
	fd_LiquidityPool_token0 = md_LiquidityPool.Fields().ByName("token0")
	fd_LiquidityPool_token1 = md_LiquidityPool.Fields().ByName("token1")
	fd_LiquidityPool_amount0 = md_LiquidityPool.Fields().ByName("amount0")
	fd_LiquidityPool_amount1 = md_LiquidityPool.Fields().ByName("amount1")
	fd_LiquidityPool_totalShares = md_LiquidityPool.Fields().ByName("totalShares")
}

var _ protoreflect.Message = (*fastReflection_LiquidityPool)(nil)

type fastReflection_LiquidityPool LiquidityPool

func (x *LiquidityPool) ProtoReflect() protoreflect.Message {
	return (*fastReflection_LiquidityPool)(x)
}

func (x *LiquidityPool) slowProtoReflect() protoreflect.Message {
	mi := &file_cosmuni_dex_liquidity_pool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_LiquidityPool_messageType fastReflection_LiquidityPool_messageType
var _ protoreflect.MessageType = fastReflection_LiquidityPool_messageType{}

type fastReflection_LiquidityPool_messageType struct{}

func (x fastReflection_LiquidityPool_messageType) Zero() protoreflect.Message {
	return (*fastReflection_LiquidityPool)(nil)
}
func (x fastReflection_LiquidityPool_messageType) New() protoreflect.Message {
	return new(fastReflection_LiquidityPool)
}
func (x fastReflection_LiquidityPool_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_LiquidityPool
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_LiquidityPool) Descriptor() protoreflect.MessageDescriptor {
	return md_LiquidityPool
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_LiquidityPool) Type() protoreflect.MessageType {
	return _fastReflection_LiquidityPool_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_LiquidityPool) New() protoreflect.Message {
	return new(fastReflection_LiquidityPool)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_LiquidityPool) Interface() protoreflect.ProtoMessage {
	return (*LiquidityPool)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_LiquidityPool) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_LiquidityPool_index, value) {
			return
		}
	}
	if x.Token0 != "" {
		value := protoreflect.ValueOfString(x.Token0)
		if !f(fd_LiquidityPool_token0, value) {
			return
		}
	}
	if x.Token1 != "" {
		value := protoreflect.ValueOfString(x.Token1)
		if !f(fd_LiquidityPool_token1, value) {
			return
		}
	}
	if x.Amount0 != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Amount0)
		if !f(fd_LiquidityPool_amount0, value) {
			return
		}
	}
	if x.Amount1 != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Amount1)
		if !f(fd_LiquidityPool_amount1, value) {
			return
		}
	}
	if x.TotalShares != uint64(0) {
		value := protoreflect.ValueOfUint64(x.TotalShares)
		if !f(fd_LiquidityPool_totalShares, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_LiquidityPool) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "cosmuni.dex.LiquidityPool.index":
		return x.Index != ""
	case "cosmuni.dex.LiquidityPool.token0":
		return x.Token0 != ""
	case "cosmuni.dex.LiquidityPool.token1":
		return x.Token1 != ""
	case "cosmuni.dex.LiquidityPool.amount0":
		return x.Amount0 != uint64(0)
	case "cosmuni.dex.LiquidityPool.amount1":
		return x.Amount1 != uint64(0)
	case "cosmuni.dex.LiquidityPool.totalShares":
		return x.TotalShares != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmuni.dex.LiquidityPool"))
		}
		panic(fmt.Errorf("message cosmuni.dex.LiquidityPool does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidityPool) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "cosmuni.dex.LiquidityPool.index":
		x.Index = ""
	case "cosmuni.dex.LiquidityPool.token0":
		x.Token0 = ""
	case "cosmuni.dex.LiquidityPool.token1":
		x.Token1 = ""
	case "cosmuni.dex.LiquidityPool.amount0":
		x.Amount0 = uint64(0)
	case "cosmuni.dex.LiquidityPool.amount1":
		x.Amount1 = uint64(0)
	case "cosmuni.dex.LiquidityPool.totalShares":
		x.TotalShares = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmuni.dex.LiquidityPool"))
		}
		panic(fmt.Errorf("message cosmuni.dex.LiquidityPool does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_LiquidityPool) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "cosmuni.dex.LiquidityPool.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "cosmuni.dex.LiquidityPool.token0":
		value := x.Token0
		return protoreflect.ValueOfString(value)
	case "cosmuni.dex.LiquidityPool.token1":
		value := x.Token1
		return protoreflect.ValueOfString(value)
	case "cosmuni.dex.LiquidityPool.amount0":
		value := x.Amount0
		return protoreflect.ValueOfUint64(value)
	case "cosmuni.dex.LiquidityPool.amount1":
		value := x.Amount1
		return protoreflect.ValueOfUint64(value)
	case "cosmuni.dex.LiquidityPool.totalShares":
		value := x.TotalShares
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmuni.dex.LiquidityPool"))
		}
		panic(fmt.Errorf("message cosmuni.dex.LiquidityPool does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidityPool) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "cosmuni.dex.LiquidityPool.index":
		x.Index = value.Interface().(string)
	case "cosmuni.dex.LiquidityPool.token0":
		x.Token0 = value.Interface().(string)
	case "cosmuni.dex.LiquidityPool.token1":
		x.Token1 = value.Interface().(string)
	case "cosmuni.dex.LiquidityPool.amount0":
		x.Amount0 = value.Uint()
	case "cosmuni.dex.LiquidityPool.amount1":
		x.Amount1 = value.Uint()
	case "cosmuni.dex.LiquidityPool.totalShares":
		x.TotalShares = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmuni.dex.LiquidityPool"))
		}
		panic(fmt.Errorf("message cosmuni.dex.LiquidityPool does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidityPool) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "cosmuni.dex.LiquidityPool.index":
		panic(fmt.Errorf("field index of message cosmuni.dex.LiquidityPool is not mutable"))
	case "cosmuni.dex.LiquidityPool.token0":
		panic(fmt.Errorf("field token0 of message cosmuni.dex.LiquidityPool is not mutable"))
	case "cosmuni.dex.LiquidityPool.token1":
		panic(fmt.Errorf("field token1 of message cosmuni.dex.LiquidityPool is not mutable"))
	case "cosmuni.dex.LiquidityPool.amount0":
		panic(fmt.Errorf("field amount0 of message cosmuni.dex.LiquidityPool is not mutable"))
	case "cosmuni.dex.LiquidityPool.amount1":
		panic(fmt.Errorf("field amount1 of message cosmuni.dex.LiquidityPool is not mutable"))
	case "cosmuni.dex.LiquidityPool.totalShares":
		panic(fmt.Errorf("field totalShares of message cosmuni.dex.LiquidityPool is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmuni.dex.LiquidityPool"))
		}
		panic(fmt.Errorf("message cosmuni.dex.LiquidityPool does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_LiquidityPool) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "cosmuni.dex.LiquidityPool.index":
		return protoreflect.ValueOfString("")
	case "cosmuni.dex.LiquidityPool.token0":
		return protoreflect.ValueOfString("")
	case "cosmuni.dex.LiquidityPool.token1":
		return protoreflect.ValueOfString("")
	case "cosmuni.dex.LiquidityPool.amount0":
		return protoreflect.ValueOfUint64(uint64(0))
	case "cosmuni.dex.LiquidityPool.amount1":
		return protoreflect.ValueOfUint64(uint64(0))
	case "cosmuni.dex.LiquidityPool.totalShares":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmuni.dex.LiquidityPool"))
		}
		panic(fmt.Errorf("message cosmuni.dex.LiquidityPool does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_LiquidityPool) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in cosmuni.dex.LiquidityPool", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_LiquidityPool) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidityPool) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_LiquidityPool) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_LiquidityPool) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*LiquidityPool)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Token0)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Token1)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Amount0 != 0 {
			n += 1 + runtime.Sov(uint64(x.Amount0))
		}
		if x.Amount1 != 0 {
			n += 1 + runtime.Sov(uint64(x.Amount1))
		}
		if x.TotalShares != 0 {
			n += 1 + runtime.Sov(uint64(x.TotalShares))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*LiquidityPool)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.TotalShares != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TotalShares))
			i--
			dAtA[i] = 0x30
		}
		if x.Amount1 != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Amount1))
			i--
			dAtA[i] = 0x28
		}
		if x.Amount0 != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Amount0))
			i--
			dAtA[i] = 0x20
		}
		if len(x.Token1) > 0 {
			i -= len(x.Token1)
			copy(dAtA[i:], x.Token1)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Token1)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Token0) > 0 {
			i -= len(x.Token0)
			copy(dAtA[i:], x.Token0)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Token0)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*LiquidityPool)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: LiquidityPool: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: LiquidityPool: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Token0", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Token0 = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Token1", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Token1 = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Amount0", wireType)
				}
				x.Amount0 = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Amount0 |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Amount1", wireType)
				}
				x.Amount1 = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Amount1 |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
				}
				x.TotalShares = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TotalShares |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: cosmuni/dex/liquidity_pool.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiquidityPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index       string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Token0      string `protobuf:"bytes,2,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1      string `protobuf:"bytes,3,opt,name=token1,proto3" json:"token1,omitempty"`
	Amount0     uint64 `protobuf:"varint,4,opt,name=amount0,proto3" json:"amount0,omitempty"`
	Amount1     uint64 `protobuf:"varint,5,opt,name=amount1,proto3" json:"amount1,omitempty"`
	TotalShares uint64 `protobuf:"varint,6,opt,name=totalShares,proto3" json:"totalShares,omitempty"`
}

func (x *LiquidityPool) Reset() {
	*x = LiquidityPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmuni_dex_liquidity_pool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiquidityPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiquidityPool) ProtoMessage() {}

// Deprecated: Use LiquidityPool.ProtoReflect.Descriptor instead.
func (*LiquidityPool) Descriptor() ([]byte, []int) {
	return file_cosmuni_dex_liquidity_pool_proto_rawDescGZIP(), []int{0}
}

func (x *LiquidityPool) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *LiquidityPool) GetToken0() string {
	if x != nil {
		return x.Token0
	}
	return ""
}

func (x *LiquidityPool) GetToken1() string {
	if x != nil {
		return x.Token1
	}
	return ""
}

func (x *LiquidityPool) GetAmount0() uint64 {
	if x != nil {
		return x.Amount0
	}
	return 0
}

func (x *LiquidityPool) GetAmount1() uint64 {
	if x != nil {
		return x.Amount1
	}
	return 0
}

func (x *LiquidityPool) GetTotalShares() uint64 {
	if x != nil {
		return x.TotalShares
	}
	return 0
}

var File_cosmuni_dex_liquidity_pool_proto protoreflect.FileDescriptor

var file_cosmuni_dex_liquidity_pool_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x6f, 0x73, 0x6d, 0x75, 0x6e, 0x69, 0x2f, 0x64, 0x65, 0x78, 0x2f, 0x6c, 0x69,
	0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x73, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x64, 0x65, 0x78, 0x22,
	0xab, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x50, 0x6f, 0x6f,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x30, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x30, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x31, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x31, 0x12, 0x20, 0x0a, 0x0b, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x42, 0x8b, 0x01,
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x75, 0x6e, 0x69, 0x2e, 0x64, 0x65,
	0x78, 0x42, 0x12, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x50, 0x6f, 0x6f, 0x6c,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x17, 0x63, 0x6f, 0x73, 0x6d, 0x75, 0x6e, 0x69,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x75, 0x6e, 0x69, 0x2f, 0x64, 0x65, 0x78,
	0xa2, 0x02, 0x03, 0x43, 0x44, 0x58, 0xaa, 0x02, 0x0b, 0x43, 0x6f, 0x73, 0x6d, 0x75, 0x6e, 0x69,
	0x2e, 0x44, 0x65, 0x78, 0xca, 0x02, 0x0b, 0x43, 0x6f, 0x73, 0x6d, 0x75, 0x6e, 0x69, 0x5c, 0x44,
	0x65, 0x78, 0xe2, 0x02, 0x17, 0x43, 0x6f, 0x73, 0x6d, 0x75, 0x6e, 0x69, 0x5c, 0x44, 0x65, 0x78,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x43,
	0x6f, 0x73, 0x6d, 0x75, 0x6e, 0x69, 0x3a, 0x3a, 0x44, 0x65, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cosmuni_dex_liquidity_pool_proto_rawDescOnce sync.Once
	file_cosmuni_dex_liquidity_pool_proto_rawDescData = file_cosmuni_dex_liquidity_pool_proto_rawDesc
)

func file_cosmuni_dex_liquidity_pool_proto_rawDescGZIP() []byte {
	file_cosmuni_dex_liquidity_pool_proto_rawDescOnce.Do(func() {
		file_cosmuni_dex_liquidity_pool_proto_rawDescData = protoimpl.X.CompressGZIP(file_cosmuni_dex_liquidity_pool_proto_rawDescData)
	})
	return file_cosmuni_dex_liquidity_pool_proto_rawDescData
}

var file_cosmuni_dex_liquidity_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cosmuni_dex_liquidity_pool_proto_goTypes = []interface{}{
	(*LiquidityPool)(nil), // 0: cosmuni.dex.LiquidityPool
}
var file_cosmuni_dex_liquidity_pool_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cosmuni_dex_liquidity_pool_proto_init() }
func file_cosmuni_dex_liquidity_pool_proto_init() {
	if File_cosmuni_dex_liquidity_pool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cosmuni_dex_liquidity_pool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiquidityPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cosmuni_dex_liquidity_pool_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cosmuni_dex_liquidity_pool_proto_goTypes,
		DependencyIndexes: file_cosmuni_dex_liquidity_pool_proto_depIdxs,
		MessageInfos:      file_cosmuni_dex_liquidity_pool_proto_msgTypes,
	}.Build()
	File_cosmuni_dex_liquidity_pool_proto = out.File
	file_cosmuni_dex_liquidity_pool_proto_rawDesc = nil
	file_cosmuni_dex_liquidity_pool_proto_goTypes = nil
	file_cosmuni_dex_liquidity_pool_proto_depIdxs = nil
}
